branch-defaults:
  master:
    environment: Sample-env
environment-defaults:
  Sample-env:
    branch: null
    repository: null
global:
  application_name: TwittTrends
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
